secret_key: "django-insecure-*&jy8si8ew8%-dj+^b!9ze#z5xcds-(^65as(zg2n##x=*ge#*"
debug: true  # 生产环境中应设置为 false
database:
  engine: "dj_db_conn_pool.backends.mysql"
  name: "server_bot"
  user: "root"
  password: "Zzy13152810650."
  host: "localhost"
  port: "3306"
redis:
  host: "localhost"
  port: "6379"
chroma:
  host: "82.156.184.46"
  port: "8000"