# Generated by Django 4.2.16 on 2024-10-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='face'),
        ),
    ]
