# Generated by Django 4.2.16 on 2024-10-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
        ('user', '0007_user_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='robots',
            field=models.ManyToManyField(related_name='users', to='robot.robot'),
        ),
    ]
