# Generated by Django 4.2.16 on 2024-10-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_options'),
        ('user', '0012_user_last_detected'),
    ]

    operations = [
    ]
