# Generated by Django 4.2.16 on 2024-10-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceProcessingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_image_path', models.CharField(max_length=255)),
                ('processed_frame_path', models.CharField(max_length=255)),
                ('key_points_image_path', models.CharField(max_length=255)),
                ('identity', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('embedding', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UnknownFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image_path', models.CharField(max_length=255)),
                ('embedding', models.JSONField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unknown_faces', to='face_recognition.faceprocessingrecord')),
            ],
        ),
    ]
